### ISSUE TITLE
List all availability zones for ease of use

### ISSUE THREAD

**Issue by openstacker** [catalyst-cloud/catalystcloud-docs#218]
It would be nice to list all availability zones on https://docs.catalystcloud.nz/kubernetes/storage.html for ease of use. I have seen several cases that user tried to create a storage class based on 'nz_wlg_2' instead of the correct 'NZ-WLG-2'. Cheers.

**Comment by chelios** [comment]
Thanks Fei Long.
This has been added to the documentation.
