### ISSUE TITLE
Swift documentation on acls needs more detail

### ISSUE THREAD

**Issue by garthwilliamson** [catalyst-cloud/catalystcloud-docs#345]
The documentation for setting acls for swift is lacking some crucial details. OS_STORAGE_URL needs to either be set in the openstack rc file or set manually by users.

EXPORT OS_STORAGE_URL=${SWIFT_API}/v1/AUTH_${PROJECT_UUID}/ is the right format for this. It's possible this can be done here or in the openstack-rc file.

**Comment by adrianjarvis** [comment]
We had a customer hits this issue... I'll update the docs.

**Comment by adrianjarvis** [comment]
Discovered this has been done, I'll added a PR to make it stand out more.
